/* Lingua Fun · Juegos extra · solo Francés e Italiano */
(function(){
'use strict';
const DATA={
 fr:{A1:[['Merci','Gracias','Le serveur m’a remercié.','El camarero me dio las gracias.'],['Bonjour','Hola','Le serveur me dit bonjour.','El camarero me saluda.'],['eau','agua','Je bois de l’eau au restaurant.','Bebo agua en el restaurante.'],['livre','libro','Je lis un livre le soir.','Leo un libro por la noche.'],['famille','familia','Ma famille habite près d’ici.','Mi familia vive cerca de aquí.'],['travail','trabajo','Je vais au travail à huit heures.','Voy al trabajo a las ocho.']],A2:[['addition','cuenta','Je demande l’addition, s’il vous plaît.','Pido la cuenta, por favor.'],['réservation','reserva','J’ai une réservation pour deux personnes.','Tengo una reserva para dos personas.'],['retard','retraso','Notre train a du retard.','Nuestro tren lleva retraso.'],['médecin','médico','Je dois prendre rendez-vous avec le médecin.','Tengo que pedir cita con el médico.'],['projet','proyecto','Je dois terminer ce projet aujourd’hui.','Tengo que terminar este proyecto hoy.'],['pluie','lluvia','Il va pleuvoir demain.','Mañana va a llover.']],B1:[['expérience','experiencia','Cette expérience m’a beaucoup appris.','Esta experiencia me enseñó mucho.'],['convaincre','convencer','Il a essayé de me convaincre.','Intentó convencerme.'],['équipe','equipo','Notre équipe travaille bien ensemble.','Nuestro equipo trabaja bien unido.'],['confidentialité','privacidad','La confidentialité est importante sur Internet.','La privacidad es importante en Internet.'],['éviter','evitar','Il faut éviter de perdre du temps.','Hay que evitar perder el tiempo.'],['protéger','proteger','Nous devons protéger l’environnement.','Debemos proteger el medio ambiente.']]},
 it:{A1:[['grazie','gracias','Il cameriere mi ha ringraziato.','El camarero me dio las gracias.'],['ciao','hola/adiós','Il mio amico mi dice ciao.','Mi amigo me saluda.'],['acqua','agua','Bevo un bicchiere d’acqua.','Bebo un vaso de agua.'],['libro','libro','Leggo un libro ogni sera.','Leo un libro todas las noches.'],['famiglia','familia','La mia famiglia vive qui.','Mi familia vive aquí.'],['lavoro','trabajo','Vado al lavoro alle otto.','Voy al trabajo a las ocho.']],A2:[['cameriere','camarero','Il cameriere mi porta il conto.','El camarero me trae la cuenta.'],['prenotare','reservar','Vorrei prenotare un tavolo per due.','Quisiera reservar una mesa para dos.'],['ritardo','retraso','Il treno è in ritardo.','El tren lleva retraso.'],['medico','médico','Devo parlare con il medico.','Tengo que hablar con el médico.'],['progetto','proyecto','Devo finire questo progetto oggi.','Tengo que terminar este proyecto hoy.'],['domani','mañana','Domani andrò in centro.','Mañana iré al centro.']],B1:[['esperienza','experiencia','È stata un’esperienza importante.','Fue una experiencia importante.'],['convincere','convencer','Ha cercato di convincermi.','Intentó convencerme.'],['squadra','equipo','La nostra squadra lavora bene insieme.','Nuestro equipo trabaja bien unida.'],['privacy','privacidad','La privacy è importante online.','La privacidad es importante en Internet.'],['evitare','evitar','Dobbiamo evitare di perdere tempo.','Debemos evitar perder tiempo.'],['proteggere','proteger','Dobbiamo proteggere l’ambiente.','Debemos proteger el medio ambiente.']]}
};
const EXTRAS={
fr:{A1:[['Je bois de l’eau.','Bebo agua.'],['Je lis un livre.','Leo un libro.'],['Ma famille est grande.','Mi familia es grande.'],['Je vais au travail.','Voy al trabajo.']],A2:[['Je demande l’addition.','Pido la cuenta.'],['Notre train a du retard.','Nuestro tren lleva retraso.'],['Je dois appeler le médecin.','Tengo que llamar al médico.'],['Je vais visiter Paris demain.','Voy a visitar París mañana.']],B1:[['Nous devons protéger l’environnement.','Debemos proteger el medio ambiente.'],['Je ne suis pas d’accord avec cette idée.','No estoy de acuerdo con esta idea.'],['Cette expérience m’a beaucoup appris.','Esta experiencia me enseñó mucho.'],['Il faudrait réduire notre consommation.','Habría que reducir nuestro consumo.']]},
it:{A1:[['Bevo un bicchiere d’acqua.','Bebo un vaso de agua.'],['Leggo un libro ogni sera.','Leo un libro todas las noches.'],['La mia famiglia vive qui.','Mi familia vive aquí.'],['Vado al lavoro alle otto.','Voy al trabajo a las ocho.']],A2:[['Vorrei prenotare un tavolo per due.','Quisiera reservar una mesa para dos.'],['Il treno è in ritardo.','El tren lleva retraso.'],['Devo parlare con il medico.','Tengo que hablar con el médico.'],['Domani andrò in centro.','Mañana iré al centro.']],B1:[['Dobbiamo proteggere l’ambiente.','Debemos proteger el medio ambiente.'],['Non sono completamente d’accordo con te.','No estoy completamente de acuerdo contigo.'],['È stata un’esperienza importante.','Fue una experiencia importante.'],['Dovremmo ridurre il consumo di energia.','Deberíamos reducir el consumo de energía.']]}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function lang(){return location.pathname.includes('frances')?'fr':'it'}
function course(){let txt=(document.body.innerText||'').toLowerCase();if(/\bb1\b/.test(txt))return'B1';if(/\ba2\b/.test(txt))return'A2';return'A1'}
function speak(t,l){if(window.speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang=l==='fr'?'fr-FR':'it-IT';u.rate=.8;speechSynthesis.speak(u)}}
function speakEs(t){if(window.speakSpanish){window.speakSpanish(t)}else if(window.speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='es-ES';u.rate=.9;speechSynthesis.speak(u)}}
function mount(){let card=document.querySelector('.fr-card,.it-card');if(!card||document.getElementById('extraGames')){setTimeout(mount,500);return}let box=document.createElement('div');box.id='extraGames';box.className='extra-games-wrap';box.innerHTML='<button class="extra-games-btn">🎮 Más juegos</button><div class="extra-games-menu" hidden><button class="extra-game-btn" data-g="pairs">🧩 Encuentra las parejas</button><button class="extra-game-btn" data-g="listen">🎧 Escucha y elige</button><button class="extra-game-btn" data-g="order">🔤 Ordena la frase</button><button class="extra-game-btn" data-g="situation">🎭 Situación real</button><button class="extra-game-btn" data-g="meaning">🧠 ¿Qué palabra es?</button></div>';
card.appendChild(box);box.querySelector('.extra-games-btn').onclick=()=>box.querySelector('.extra-games-menu').hidden=!box.querySelector('.extra-games-menu').hidden;box.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>openGame(b.dataset.g));}
function openGame(type){let l=lang(),c=course(),root=document.getElementById('app'),data=DATA[l][c];let back='<button class="extra-back" id="xback">← Volver</button>';if(type==='pairs')pairs(l,c,root,back,data);else if(type==='listen')listen(l,c,root,back,data);else if(type==='order')order(l,c,root,back);else if(type==='situation')situation(l,c,root,back);else meaning(l,c,root,back,data)}
function shell(title,content,back){document.getElementById('app').innerHTML='<div class="'+(lang()==='fr'?'fr-card':'it-card')+' extra-game-card"><div class="it-top"><span>🎮 '+title+'</span></div>'+content+back+'</div>';document.getElementById('xback').onclick=()=>location.reload()}
function pairs(l,c,root,back,data){let items=shuffle(data).slice(0,4),cards=shuffle(items.flatMap((x,i)=>[{id:i,text:x[0],type:'a'},{id:i,text:x[1],type:'b'}]));let html='<p>Une cada palabra con su significado. Los aciertos se mantienen.</p><div class="extra-pairs">'+cards.map((x,i)=>'<button class="extra-pair" data-i="'+i+'">'+x.text+'</button>').join('')+'</div><div id="pairFb" class="extra-feedback"></div>';shell('Encuentra las parejas',html,back);let sel=[],done=0;document.querySelectorAll('.extra-pair').forEach((b,i)=>b.onclick=()=>{if(b.disabled)return;b.classList.add('revealed');speak(b.textContent,l);sel.push({b,i,card:cards[i]});if(sel.length===2){let[a,z]=sel;if(a.card.id===z.card.id&&a.card.type!==z.card.type){a.b.classList.add('matched');z.b.classList.add('matched');a.b.disabled=z.b.disabled=true;done++;document.getElementById('pairFb').innerHTML='✅ ¡Pareja correcta!'+(done===4?' 🎉 ¡Completado!':'')}else{document.getElementById('pairFb').innerHTML='❌ No coinciden, prueba otra vez.';setTimeout(()=>{a.b.classList.remove('revealed');z.b.classList.remove('revealed')},650)}sel=[]}})}
function listen(l,c,root,back,data){let items=shuffle(data).slice(0,4),i=0;function render(){let x=items[i],opts=shuffle([x[3],...shuffle(data.filter(y=>y!==x).map(y=>y[3])).slice(0,3)]);shell('Escucha y elige','<p>Escucha la frase y elige su significado.</p><button class="extra-game-btn" id="play">🔊 Escuchar frase</button><div class="extra-game-answers">'+opts.map(o=>'<button>'+o+'</button>').join('')+'</div><div id="ef" class="extra-feedback"></div><p class="extra-small">Pregunta '+(i+1)+' de 4</p>',back);document.getElementById('play').onclick=()=>speak(x[2],l);setTimeout(()=>speak(x[2],l),150);document.querySelectorAll('.extra-game-answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.extra-game-answers button').forEach(q=>q.disabled=true);let ok=b.textContent===x[3];document.getElementById('ef').className='extra-feedback '+(ok?'extra-ok':'extra-bad');document.getElementById('ef').innerHTML=ok?'✅ Correcto<br><b>'+x[2]+'</b>':'❌ Correcto: <b>'+x[3]+'</b><br>'+x[2];speak(x[2],l);setTimeout(()=>{i++;i<4?render():shell('Escucha y elige','<h2>🎉 Juego completado</h2><p>Has terminado las 4 preguntas.</p>',back)},2500)})}render()}
function order(l,c,root,back){let items=shuffle(EXTRAS[l][c]).slice(0,4),i=0;function render(){let [sent,sp]=items[i],words=shuffle(sent.replace(/[¿?¡!.,]/g,'').split(/\s+/)),chosen=[];shell('Ordena la frase','<p>Forma la frase correcta.</p><div id="chosen" class="extra-current">Toca las palabras en orden.</div><div id="tokens" class="extra-order">'+words.map((w,j)=>'<button class="extra-token" data-j="'+j+'">'+w+'</button>').join('')+'</div><button class="extra-game-btn" id="check">Comprobar</button><div id="of" class="extra-feedback"></div><p class="extra-small">Frase '+(i+1)+' de 4</p>',back);let cur=document.getElementById('chosen');document.querySelectorAll('.extra-token').forEach(b=>b.onclick=()=>{if(b.disabled)return;chosen.push(b.textContent);b.disabled=true;cur.textContent=chosen.join(' ')});document.getElementById('check').onclick=()=>{let ok=chosen.join(' ' )===sent.replace(/[¿?¡!.,]/g,'').split(/\s+/).join(' ');document.getElementById('of').className='extra-feedback '+(ok?'extra-ok':'extra-bad');document.getElementById('of').innerHTML=ok?'✅ ¡Muy bien!<br>'+sent+'<br>'+sp:'❌ Orden correcto:<br><b>'+sent+'</b><br>'+sp;speak(sent,l);setTimeout(()=>{i++;i<4?render():shell('Ordena la frase','<h2>🎉 ¡Completado!</h2><p>Has ordenado las 4 frases.</p>',back)},3000)}}render()}
function situation(l,c,root,back){let items=DATA[l][c],i=0;function render(){let x=items[i],wrong=shuffle(items.filter(y=>y!==x).map(y=>y[2])).slice(0,3),opts=shuffle([x[2],...wrong]);shell('Situación real','<p><b>Situación:</b> Estás en una situación cotidiana y quieres usar esta expresión:</p><h2>'+x[0]+'</h2><div class="extra-game-answers">'+opts.map(o=>'<button>'+o+'</button>').join('')+'</div><div id="sf" class="extra-feedback"></div><p class="extra-small">Situación '+(i+1)+' de 4</p>',back);document.querySelectorAll('.extra-game-answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.extra-game-answers button').forEach(q=>q.disabled=true);let ok=b.textContent===x[2];document.getElementById('sf').className='extra-feedback '+(ok?'extra-ok':'extra-bad');document.getElementById('sf').innerHTML=ok?'✅ Respuesta natural.<br>🇪🇸 '+x[3]:'❌ Una respuesta natural sería:<br><b>'+x[2]+'</b><br>🇪🇸 '+x[3];speak(x[2],l);setTimeout(()=>{i++;i<4?render():shell('Situación real','<h2>🎉 ¡Completado!</h2>',back)},2800)})}render()}
function meaning(l,c,root,back,data){let items=shuffle(data),i=0;function render(){let x=items[i],opts=shuffle([x[1],...shuffle(data.filter(y=>y!==x).map(y=>y[1])).slice(0,3)]);shell('¿Qué palabra es?','<p>Escucha la palabra y elige su significado.</p><button class="extra-game-btn" id="play">🔊 Escuchar</button><h2>'+x[0]+'</h2><div class="extra-game-answers">'+opts.map(o=>'<button>'+o+'</button>').join('')+'</div><div id="mf" class="extra-feedback"></div>',back);document.getElementById('play').onclick=()=>speak(x[0],l);setTimeout(()=>speak(x[0],l),120);document.querySelectorAll('.extra-game-answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.extra-game-answers button').forEach(q=>q.disabled=true);let ok=b.textContent===x[1];document.getElementById('mf').className='extra-feedback '+(ok?'extra-ok':'extra-bad');document.getElementById('mf').innerHTML=ok?'✅ Correcto':'❌ Correcto: <b>'+x[1]+'</b>';setTimeout(()=>{i++;i<4?render():shell('¿Qué palabra es?','<h2>🎉 ¡Completado!</h2>',back)},2200)})}render()}
mount();
})();
