const IT_STATE_KEY='englishFunItalianState';
const topics=['Saludos y cortesía','Personas y familia','Casa','Ciudad','Comida y bebida','Rutinas','Tiempo','Verbos básicos','Adjetivos','Repaso 1','Viajes','Compras','Restaurante','Trabajo y estudios','Tiempo libre','Opiniones sencillas','Pasado básico','Planes','Situaciones prácticas','Misión final'];
const levels=[
[['ciao','hola / adiós'],['buongiorno','buenos días'],['buonasera','buenas tardes / noches'],['grazie','gracias'],['per favore','por favor'],['arrivederci','adiós'],['sì','sí'],['no','no']],
[['amico','amigo'],['amica','amiga'],['famiglia','familia'],['madre','madre'],['padre','padre'],['fratello','hermano'],['sorella','hermana'],['bambino','niño']],
[['casa','casa'],['stanza','habitación'],['cucina','cocina'],['bagno','baño'],['porta','puerta'],['finestra','ventana'],['letto','cama'],['tavolo','mesa']],
[['città','ciudad'],['strada','calle'],['piazza','plaza'],['stazione','estación'],['scuola','escuela'],['negozio','tienda'],['parco','parque'],['ospedale','hospital']],
[['acqua','agua'],['pane','pan'],['latte','leche'],['caffè','café'],['pizza','pizza'],['pasta','pasta'],['mela','manzana'],['vino','vino']],
[['alzarsi','levantarse'],['mangiare','comer'],['bere','beber'],['lavorare','trabajar'],['studiare','estudiar'],['dormire','dormir'],['andare','ir'],['tornare','volver']],
[['oggi','hoy'],['domani','mañana'],['ieri','ayer'],['mattina','mañana'],['pomeriggio','tarde'],['sera','tarde / noche'],['settimana','semana'],['mese','mes']],
[['essere','ser / estar'],['avere','tener'],['fare','hacer'],['andare','ir'],['venire','venir'],['dire','decir'],['sapere','saber'],['potere','poder']],
[['grande','grande'],['piccolo','pequeño'],['buono','bueno'],['cattivo','malo'],['facile','fácil'],['difficile','difícil'],['bello','bonito'],['stanco','cansado']],
[['Mi chiamo Marco.','Me llamo Marco.'],['Come stai?','¿Cómo estás?'],['Sto bene, grazie.','Estoy bien, gracias.'],['Dove abiti?','¿Dónde vives?'],['Abito a Roma.','Vivo en Roma.'],['Che cosa fai?','¿Qué haces?'],['Mi piace la musica.','Me gusta la música.'],['Non capisco.','No entiendo.']],
[['viaggio','viaje'],['biglietto','billete'],['aeroporto','aeropuerto'],['treno','tren'],['albergo','hotel'],['camera','habitación'],['valigia','maleta'],['vacanza','vacaciones']],
[['comprare','comprar'],['vendere','vender'],['prezzo','precio'],['caro','caro'],['economico','barato'],['taglia','talla'],['scarpe','zapatos'],['maglietta','camiseta']],
[['menù','menú'],['cameriere','camarero'],['conto','cuenta'],['colazione','desayuno'],['pranzo','comida'],['cena','cena'],['senza','sin'],['Vorrei un caffè, per favore.','Quisiera un café, por favor.']],
[['lavoro','trabajo'],['ufficio','oficina'],['collega','compañero de trabajo'],['riunione','reunión'],['studente','estudiante'],['insegnante','profesor'],['corso','curso'],['esame','examen']],
[['musica','música'],['film','película'],['libro','libro'],['cinema','cine'],['teatro','teatro'],['sport','deporte'],['passeggiata','paseo'],['giocare','jugar']],
[['secondo me','en mi opinión'],['penso che','pienso que'],['mi piace','me gusta'],['non mi piace','no me gusta'],['perché','porque'],['ma','pero'],['anche','también'],['quindi','por lo tanto / así que']],
[['sono stato','he estado / estuve'],['ho mangiato','he comido / comí'],['ho visto','he visto / vi'],['ho fatto','he hecho / hice'],['sono andato','he ido / fui'],['ieri sera','anoche'],['la settimana scorsa','la semana pasada'],['Ho visitato Roma.','Visité Roma.']],
[['domani','mañana'],['presto','pronto'],['più tardi','más tarde'],['weekend','fin de semana'],['programma','plan'],['decidere','decidir'],['volere','querer'],['Vorrei visitare Firenze.','Quisiera visitar Florencia.']],
[['scusi','perdone / disculpe'],['mi può aiutare?','¿me puede ayudar?'],['cerco','busco'],['ho bisogno di','necesito'],['quanto costa?','¿cuánto cuesta?'],['non lo so','no lo sé'],['va bene','está bien'],['Non c’è problema.','No hay problema.']],
[['però','sin embargo / pero'],['per questo','por eso'],['prima','antes'],['dopo','después'],['sempre','siempre'],['spesso','a menudo'],['a volte','a veces'],['Sto imparando l’italiano.','Estoy aprendiendo italiano.']]
];
let state=JSON.parse(localStorage.getItem(IT_STATE_KEY)||'null')||{level:0,completed:[],xp:0};
state.level=Number.isInteger(state.level)?state.level:0;state.completed=Array.isArray(state.completed)?state.completed:[];state.xp=Number(state.xp||0);
function save(){localStorage.setItem(IT_STATE_KEY,JSON.stringify(state));update();}
function update(){const xp=document.getElementById('xp'),p=document.getElementById('progress');if(xp)xp.textContent=state.xp;if(p)p.style.width=(state.completed.length/20*100)+'%';}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function speakItalian(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='it-IT';u.rate=.78;const voices=window.speechSynthesis.getVoices();const v=voices.find(x=>/^it-IT$/i.test(x.lang))||voices.find(x=>/^it[-_]/i.test(x.lang));if(v)u.voice=v;window.speechSynthesis.speak(u)}
function speakSpanish(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='es-ES';u.rate=.90;const voices=window.speechSynthesis.getVoices();const v=voices.find(x=>/^es-ES$/i.test(x.lang))||voices.find(x=>/^es[-_]/i.test(x.lang));if(v)u.voice=v;window.speechSynthesis.speak(u)}
function exampleFor(word){const map={
'ciao':'Ciao, come stai?', 'buongiorno':'Buongiorno, signora!', 'buonasera':'Buonasera, come sta?', 'grazie':'Il cameriere mi ha ringraziato.', 'per favore':'Un caffè, per favore.', 'arrivederci':'Arrivederci, a domani!', 'sì':'Sì, va bene.', 'no':'No, grazie.',
'amico':'Il mio amico vive a Roma.', 'amica':'La mia amica lavora qui.', 'famiglia':'La mia famiglia vive vicino a Milano.', 'madre':'Mia madre cucina molto bene.', 'padre':'Mio padre lavora in ufficio.', 'fratello':'Mio fratello ha vent’anni.', 'sorella':'Mia sorella studia italiano.', 'bambino':'Il bambino gioca nel parco.',
'casa':'La mia casa è vicino al centro.', 'stanza':'La mia stanza è molto luminosa.', 'cucina':'La cucina è piccola ma comoda.', 'bagno':'Il bagno è al primo piano.', 'porta':'La porta è aperta.', 'finestra':'La finestra è chiusa.', 'letto':'Il libro è sul letto.', 'tavolo':'Le chiavi sono sul tavolo.',
'città':'La mia città è molto tranquilla.', 'strada':'Questa strada porta alla stazione.', 'piazza':'Ci vediamo in piazza alle otto.', 'stazione':'La stazione è vicino al centro.', 'scuola':'I bambini vanno a scuola ogni mattina.', 'negozio':'Il negozio chiude alle otto.', 'parco':'Vado al parco con i miei amici.', 'ospedale':'L’ospedale è vicino alla stazione.',
'acqua':'Bevo molta acqua durante il giorno.', 'pane':'Compro il pane ogni mattina.', 'latte':'Prendo il latte a colazione.', 'caffè':'Prendo un caffè dopo pranzo.', 'pizza':'Stasera mangiamo una pizza.', 'pasta':'Mia madre prepara la pasta.', 'mela':'Mangio una mela ogni pomeriggio.', 'vino':'A cena bevo un bicchiere di vino.',
'alzarsi':'Di solito mi alzo alle sette.', 'mangiare':'Mi piace mangiare la pasta.', 'bere':'Voglio bere un bicchiere d’acqua.', 'lavorare':'Lavoro in centro ogni giorno.', 'studiare':'Studio italiano ogni sera.', 'dormire':'Vado a dormire alle undici.', 'andare':'Vado al lavoro in autobus.', 'tornare':'Torno a casa alle sei.',
'oggi':'Oggi lavoro fino alle cinque.', 'domani':'Domani vado a Roma.', 'ieri':'Ieri sono rimasto a casa.', 'mattina':'La mattina bevo un caffè.', 'pomeriggio':'Nel pomeriggio studio italiano.', 'sera':'La sera guardo un film.', 'settimana':'Questa settimana lavoro molto.', 'mese':'Il prossimo mese andiamo in vacanza.',
'essere':'Sono molto stanco oggi.', 'avere':'Ho una macchina nuova.', 'fare':'Faccio colazione alle sette.', 'venire':'Vieni a casa mia stasera?', 'dire':'Non so cosa dire.', 'sapere':'Non so dove abita.', 'potere':'Posso aiutarti domani?',
'grande':'La città è molto grande.', 'piccolo':'Il mio appartamento è piccolo.', 'buono':'Questo ristorante è molto buono.', 'cattivo':'Oggi il tempo è cattivo.', 'facile':'Questo esercizio è facile.', 'difficile':'L’italiano non è difficile.', 'bello':'È un posto molto bello.', 'stanco':'Sono stanco dopo il lavoro.',
'Mi chiamo Marco.':'Mi chiamo Marco e vivo a Roma.', 'Come stai?':'Come stai oggi?', 'Sto bene, grazie.':'Sto bene, grazie. E tu?', 'Dove abiti?':'Dove abiti adesso?', 'Abito a Roma.':'Abito a Roma con la mia famiglia.', 'Che cosa fai?':'Che cosa fai nel tempo libero?', 'Mi piace la musica.':'Mi piace la musica italiana.', 'Non capisco.':'Non capisco questa parola.',
'viaggio':'Il viaggio è stato fantastico.', 'biglietto':'Ho comprato un biglietto del treno.', 'aeroporto':'L’aeroporto è lontano dal centro.', 'treno':'Il treno parte alle nove.', 'albergo':'Abbiamo prenotato un albergo vicino al mare.', 'camera':'La camera dell’albergo è molto grande.', 'valigia':'La mia valigia è pesante.', 'vacanza':'In estate facciamo una vacanza in Italia.',
'comprare':'Voglio comprare una maglietta.', 'vendere':'Questo negozio vende scarpe italiane.', 'prezzo':'Il prezzo è troppo alto.', 'caro':'Questo ristorante è troppo caro.', 'economico':'Questo hotel è semplice ma economico.', 'taglia':'Avete una taglia più grande?', 'scarpe':'Le mie scarpe sono nuove.', 'maglietta':'Questa maglietta è molto bella.',
'menù':'Posso vedere il menù, per favore?', 'cameriere':'Il cameriere mi ha portato il conto.', 'conto':'Il conto, per favore.', 'colazione':'La colazione è alle otto.', 'pranzo':'A pranzo mangio la pasta.', 'cena':'A cena mangiamo insieme.', 'senza':'Un caffè senza zucchero, per favore.', 'Vorrei un caffè, per favore.':'Vorrei un caffè, per favore.',
'lavoro':'Sono al lavoro fino alle sei.', 'ufficio':'Il mio ufficio è vicino alla stazione.', 'collega':'Il mio collega lavora con me.', 'riunione':'Ho una riunione alle dieci.', 'studente':'Sono uno studente di italiano.', 'insegnante':'La mia insegnante parla molto lentamente.', 'corso':'Frequento un corso di italiano.', 'esame':'Domani ho un esame importante.',
'musica':'Ascolto la musica ogni sera.', 'film':'Stasera guardo un film italiano.', 'libro':'Sto leggendo un libro interessante.', 'cinema':'Sabato andiamo al cinema.', 'teatro':'Stasera andiamo a teatro.', 'sport':'Faccio sport tre volte alla settimana.', 'passeggiata':'Faccio una passeggiata dopo cena.', 'giocare':'I bambini giocano nel parco.',
'secondo me':'Secondo me è una buona idea.', 'penso che':'Penso che sia interessante.', 'mi piace':'Mi piace molto questa città.', 'non mi piace':'Non mi piace aspettare.', 'perché':'Resto a casa perché piove.', 'ma':'Vorrei venire, ma oggi lavoro.', 'anche':'Anche io voglio andare.', 'quindi':'È tardi, quindi torno a casa.',
'sono stato':'Sono stato a Roma l’anno scorso.', 'ho mangiato':'Ho mangiato una pizza ieri sera.', 'ho visto':'Ho visto un film molto bello.', 'ho fatto':'Ho fatto una passeggiata ieri.', 'sono andato':'Sono andato al cinema con Marco.', 'ieri sera':'Ieri sera ho cenato fuori.', 'la settimana scorsa':'La settimana scorsa ero in vacanza.', 'Ho visitato Roma.':'Ho visitato Roma l’estate scorsa.',
'presto':'Devo alzarmi presto domani.', 'più tardi':'Ti chiamo più tardi.', 'weekend':'Nel weekend vado al mare.', 'programma':'Qual è il programma per domani?', 'decidere':'Dobbiamo decidere oggi.', 'volere':'Voglio imparare l’italiano.', 'Vorrei visitare Firenze.':'Vorrei visitare Firenze in primavera.',
'scusi':'Scusi, dov’è la stazione?', 'mi può aiutare?':'Mi può aiutare, per favore?', 'cerco':'Cerco un albergo economico.', 'ho bisogno di':'Ho bisogno di un’informazione.', 'quanto costa?':'Quanto costa questa maglietta?', 'non lo so':'Non lo so, mi dispiace.', 'va bene':'Va bene, ci vediamo domani.', 'Non c’è problema.':'Non c’è problema, posso aspettare.',
'però':'Vorrei venire, però sono stanco.', 'per questo':'Piove, per questo resto a casa.', 'prima':'Prima faccio colazione, dopo vado al lavoro.', 'dopo':'Dopo cena guardo un film.', 'sempre':'Vado sempre al lavoro in autobus.', 'spesso':'Vado spesso al cinema.', 'a volte':'A volte cucino per tutta la famiglia.', 'Sto imparando l’italiano.':'Sto imparando l’italiano perché mi piace.'
};if(map[word])return map[word];return word.includes(' ')?word:`Posso usare «${word}» in una frase, per esempio: «${word} è una parola molto utile in italiano».`;}

function meaningOf(fr){for(const l of levels){const x=l.find(v=>v[0]===fr);if(x)return x[1]}return ''}
function showMap(){document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-header"><div><h1>🇮🇹 Italiano A1</h1><p>Primer módulo de italiano, desde cero y con dificultad progresiva.</p></div><div class="it-stats">⭐ <b id="xp">${state.xp}</b> XP</div></div><div class="it-progress"><div id="progress"></div></div><div class="it-levels">${topics.map((t,i)=>`<button class="it-level ${state.completed.includes(i)?'done':''} ${i<=state.level?'open':'locked'}" ${i<=state.level?'':'disabled'} data-level="${i}"><b>${i+1}</b><span>${t}</span><small>${state.completed.includes(i)?'✓ Completado':i===state.level?'▶ Empezar':'🔒 Bloqueado'}</small></button>`).join('')}</div><div class="it-unlock"><p>🇮🇹 Italiano A1 · DISPONIBLE AHORA · A2 y B1 próximamente</p></div><button class="it-back" id="backHome">← Volver al selector</button></div>`;update();document.querySelectorAll('.it-level[data-level]').forEach(b=>b.addEventListener('click',()=>startLevel(Number(b.dataset.level))));document.getElementById('backHome').addEventListener('click',()=>location.href='index.html')}
function startLevel(n){const q=shuffle(levels[n]||levels[0]).slice(0,4);let i=0,correct=0,locked=false,timer=null;function render(){locked=false;const [fr,es]=q[i];const all=levels.flat();const opts=shuffle([es,...shuffle(all).filter(x=>x[1]!==es).slice(0,3).map(x=>x[1])]);document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-top"><button class="it-back" id="back">← Niveles</button><span>🇮🇹 A1 · ${topics[n]}</span></div><div class="it-question-tag">Nivel A1 · Vocabulario</div><h2>${fr}</h2><button class="it-listen" id="listen">🔊 Escuchar en italiano</button><p>¿Qué significa?</p><div class="it-answers" id="answers">${opts.map(o=>`<button type="button">${o}</button>`).join('')}</div><div id="feedback"></div><small>Pregunta ${i+1} de ${q.length}</small></div>`;document.getElementById('back').addEventListener('click',()=>{if(timer)clearTimeout(timer);window.speechSynthesis?.cancel();showMap()});document.getElementById('listen').addEventListener('click',()=>speakItalian(fr));setTimeout(()=>speakItalian(fr),180);document.querySelectorAll('#answers button').forEach(b=>b.addEventListener('click',()=>{if(locked)return;locked=true;document.querySelectorAll('#answers button').forEach(x=>x.disabled=true);answer(b.textContent,es,n)}))}function answer(a,c,ln){const fb=document.getElementById('feedback');const ok=a===c;if(ok)correct++;state.xp+=ok?10:0;const ex=exampleFor(q[i][0]),m=meaningOf(q[i][0]);fb.innerHTML=ok?`<div class="it-example">✅ <b>¡Muy bien!</b><br>🗣️ <b>En una frase:</b> ${ex}<br><span class="it-meaning">${m}</span></div><button class="it-listen" id="exListen">🔊 Escuchar la frase en italiano</button><button class="it-listen" id="esListen">🇪🇸 Escuchar en español</button><div class="it-next">⏱️ Siguiente pregunta en 4 segundos…</div>`:`<div class="it-example">❌ <b>Correcto: ${c}</b><br>🗣️ <b>En una frase:</b> ${ex}<br><span class="it-meaning">${m}</span></div><button class="it-listen" id="exListen">🔊 Escuchar la frase en italiano</button><button class="it-listen" id="esListen">🇪🇸 Escuchar en español</button><div class="it-next">⏱️ Siguiente pregunta en 4 segundos…</div>`;document.getElementById('exListen').addEventListener('click',()=>speakItalian(ex));document.getElementById('esListen').addEventListener('click',()=>speakSpanish(m));speakItalian(ex);save();timer=setTimeout(()=>{timer=null;i++;i<q.length?render():completeLevel(ln,correct,q.length)},4000)}render()}
function completeLevel(n,correct,total){if(!state.completed.includes(n))state.completed.push(n);if(n<19)state.level=Math.max(state.level,n+1);state.xp+=50;save();document.getElementById('app').innerHTML=`<div class="it-card center"><div class="it-big">🎉</div><h2>¡Nivel completado!</h2><p>Has acertado ${correct} de ${total}.</p><p>⭐ +50 XP</p>${state.completed.length>=20?'<div class="it-unlock"><h3>🏆 ¡Has terminado Italiano A1!</h3><p>Italiano A1 completado. A2 y B1 se añadirán próximamente.</p></div>':''}<button class="it-main" id="cont">Continuar</button></div>`;document.getElementById('cont').addEventListener('click',showMap)}
showMap();
