const IT_STATE_KEY='englishFunItalianState';
const topics=['Saludos y cortesía','Personas y familia','Casa','Ciudad','Comida y bebida','Rutinas','Tiempo','Verbos básicos','Adjetivos','Repaso 1','Viajes','Compras','Restaurante','Trabajo y estudios','Tiempo libre','Opiniones sencillas','Pasado básico','Planes','Situaciones prácticas','Misión final'];
const levels=[
[['ciao','hola / adiós'],['buongiorno','buenos días'],['buonasera','buenas tardes / noches'],['grazie','gracias'],['per favore','por favor'],['arrivederci','adiós'],['sì','sí'],['no','no']],
[['amico','amigo'],['amica','amiga'],['famiglia','familia'],['madre','madre'],['padre','padre'],['fratello','hermano'],['sorella','hermana'],['bambino','niño']],
[['casa','casa'],['stanza','habitación'],['cucina','cocina'],['bagno','baño'],['porta','puerta'],['finestra','ventana'],['letto','cama'],['tavolo','mesa']],
[['città','ciudad'],['strada','calle'],['piazza','plaza'],['stazione','estación'],['scuola','escuela'],['negozio','tienda'],['parco','parque'],['ospedale','hospital']],
[['acqua','agua'],['pane','pan'],['latte','leche'],['caffè','café'],['pizza','pizza'],['pasta','pasta'],['mela','manzana'],['vino','vino']],
[['alzarsi','levantarse'],['mangiare','comer'],['bere','beber'],['lavorare','trabajar'],['studiare','estudiar'],['dormire','dormir'],['andare','ir'],['tornare','volver']],
[['oggi','hoy'],['domani','mañana'],['ieri','ayer'],['mattina','mañana'],['pomeriggio','tarde'],['sera','tarde / noche'],['settimana','semana'],['mese','mes']],
[['essere','ser / estar'],['avere','tener'],['fare','hacer'],['andare','ir'],['venire','venir'],['dire','decir'],['sapere','saber'],['potere','poder']],
[['grande','grande'],['piccolo','pequeño'],['buono','bueno'],['cattivo','malo'],['facile','fácil'],['difficile','difícil'],['bello','bonito'],['stanco','cansado']],
[['Mi chiamo Marco.','Me llamo Marco.'],['Come stai?','¿Cómo estás?'],['Sto bene, grazie.','Estoy bien, gracias.'],['Dove abiti?','¿Dónde vives?'],['Abito a Roma.','Vivo en Roma.'],['Che cosa fai?','¿Qué haces?'],['Mi piace la musica.','Me gusta la música.'],['Non capisco.','No entiendo.']],
[['viaggio','viaje'],['biglietto','billete'],['aeroporto','aeropuerto'],['treno','tren'],['albergo','hotel'],['camera','habitación'],['valigia','maleta'],['vacanza','vacaciones']],
[['comprare','comprar'],['vendere','vender'],['prezzo','precio'],['caro','caro'],['economico','barato'],['taglia','talla'],['scarpe','zapatos'],['maglietta','camiseta']],
[['menù','menú'],['cameriere','camarero'],['conto','cuenta'],['colazione','desayuno'],['pranzo','comida'],['cena','cena'],['senza','sin'],['Vorrei un caffè, per favore.','Quisiera un café, por favor.']],
[['lavoro','trabajo'],['ufficio','oficina'],['collega','compañero de trabajo'],['riunione','reunión'],['studente','estudiante'],['insegnante','profesor'],['corso','curso'],['esame','examen']],
[['musica','música'],['film','película'],['libro','libro'],['cinema','cine'],['teatro','teatro'],['sport','deporte'],['passeggiata','paseo'],['giocare','jugar']],
[['secondo me','en mi opinión'],['penso che','pienso que'],['mi piace','me gusta'],['non mi piace','no me gusta'],['perché','porque'],['ma','pero'],['anche','también'],['quindi','por lo tanto / así que']],
[['sono stato','he estado / estuve'],['ho mangiato','he comido / comí'],['ho visto','he visto / vi'],['ho fatto','he hecho / hice'],['sono andato','he ido / fui'],['ieri sera','anoche'],['la settimana scorsa','la semana pasada'],['Ho visitato Roma.','Visité Roma.']],
[['domani','mañana'],['presto','pronto'],['più tardi','más tarde'],['weekend','fin de semana'],['programma','plan'],['decidere','decidir'],['volere','querer'],['Vorrei visitare Firenze.','Quisiera visitar Florencia.']],
[['scusi','perdone / disculpe'],['mi può aiutare?','¿me puede ayudar?'],['cerco','busco'],['ho bisogno di','necesito'],['quanto costa?','¿cuánto cuesta?'],['non lo so','no lo sé'],['va bene','está bien'],['Non c’è problema.','No hay problema.']],
[['però','sin embargo / pero'],['per questo','por eso'],['prima','antes'],['dopo','después'],['sempre','siempre'],['spesso','a menudo'],['a volte','a veces'],['Sto imparando l’italiano.','Estoy aprendiendo italiano.']]
];
let state=JSON.parse(localStorage.getItem(IT_STATE_KEY)||'null')||{level:0,completed:[],xp:0};
state.level=Number.isInteger(state.level)?state.level:0;state.completed=Array.isArray(state.completed)?state.completed:[];state.xp=Number(state.xp||0);
function save(){localStorage.setItem(IT_STATE_KEY,JSON.stringify(state));update();}
function update(){const xp=document.getElementById('xp'),p=document.getElementById('progress');if(xp)xp.textContent=state.xp;if(p)p.style.width=(state.completed.length/20*100)+'%';}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function speakItalian(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='it-IT';u.rate=.78;const voices=window.speechSynthesis.getVoices();const v=voices.find(x=>/^it-IT$/i.test(x.lang))||voices.find(x=>/^it[-_]/i.test(x.lang));if(v)u.voice=v;window.speechSynthesis.speak(u)}
function exampleFor(word){const map={'ciao':'Ciao, come stai?','grazie':'Grazie mille per il tuo aiuto.','casa':'La mia casa è piccola.','famiglia':'La mia famiglia vive qui.','acqua':'Bevo un bicchiere d’acqua.','mangiare':'Mi piace mangiare la pasta.','andare':'Vado al lavoro ogni mattina.','essere':'Sono molto stanco oggi.','avere':'Ho una macchina nuova.','grande':'La città è molto grande.','viaggio':'Il viaggio è stato fantastico.','comprare':'Vorrei comprare una maglietta.','conto':'Il conto, per favore.','lavoro':'Sono al lavoro.','musica':'Ascolto la musica ogni sera.','perché':'Resto a casa perché piove.','domani':'Domani vado a Roma.','scusi':'Scusi, dov’è la stazione?'};if(map[word])return map[word];return word.includes(' ')?word:`Uso la parola «${word}» in una frase.`}
function meaningOf(fr){for(const l of levels){const x=l.find(v=>v[0]===fr);if(x)return x[1]}return ''}
function showMap(){document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-header"><div><h1>🇮🇹 Italiano A1</h1><p>Primer módulo de italiano, desde cero y con dificultad progresiva.</p></div><div class="it-stats">⭐ <b id="xp">${state.xp}</b> XP</div></div><div class="it-progress"><div id="progress"></div></div><div class="it-levels">${topics.map((t,i)=>`<button class="it-level ${state.completed.includes(i)?'done':''} ${i<=state.level?'open':'locked'}" ${i<=state.level?'':'disabled'} data-level="${i}"><b>${i+1}</b><span>${t}</span><small>${state.completed.includes(i)?'✓ Completado':i===state.level?'▶ Empezar':'🔒 Bloqueado'}</small></button>`).join('')}</div><div class="it-unlock"><p>🇮🇹 Próximamente: A2 y B1</p></div><button class="it-back" id="backHome">← Volver al selector</button></div>`;update();document.querySelectorAll('.it-level[data-level]').forEach(b=>b.addEventListener('click',()=>startLevel(Number(b.dataset.level))));document.getElementById('backHome').addEventListener('click',()=>location.href='index.html')}
function startLevel(n){const q=shuffle(levels[n]||levels[0]).slice(0,4);let i=0,correct=0,locked=false,timer=null;function render(){locked=false;const [fr,es]=q[i];const all=levels.flat();const opts=shuffle([es,...shuffle(all).filter(x=>x[1]!==es).slice(0,3).map(x=>x[1])]);document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-top"><button class="it-back" id="back">← Niveles</button><span>🇮🇹 A1 · ${topics[n]}</span></div><div class="it-question-tag">Nivel A1 · Vocabulario</div><h2>${fr}</h2><button class="it-listen" id="listen">🔊 Escuchar en italiano</button><p>¿Qué significa?</p><div class="it-answers" id="answers">${opts.map(o=>`<button type="button">${o}</button>`).join('')}</div><div id="feedback"></div><small>Pregunta ${i+1} de ${q.length}</small></div>`;document.getElementById('back').addEventListener('click',()=>{if(timer)clearTimeout(timer);window.speechSynthesis?.cancel();showMap()});document.getElementById('listen').addEventListener('click',()=>speakItalian(fr));setTimeout(()=>speakItalian(fr),180);document.querySelectorAll('#answers button').forEach(b=>b.addEventListener('click',()=>{if(locked)return;locked=true;document.querySelectorAll('#answers button').forEach(x=>x.disabled=true);answer(b.textContent,es,n)}))}function answer(a,c,ln){const fb=document.getElementById('feedback');const ok=a===c;if(ok)correct++;state.xp+=ok?10:0;const ex=exampleFor(q[i][0]),m=meaningOf(q[i][0]);fb.innerHTML=ok?`<div class="it-example">✅ <b>¡Muy bien!</b><br>🗣️ <b>En una frase:</b> ${ex}<br><span class="it-meaning">${m}</span></div><button class="it-listen" id="exListen">🔊 Escuchar la frase</button><div class="it-next">⏱️ Siguiente pregunta en 4 segundos…</div>`:`<div class="it-example">❌ <b>Correcto: ${c}</b><br>🗣️ <b>En una frase:</b> ${ex}<br><span class="it-meaning">${m}</span></div><button class="it-listen" id="exListen">🔊 Escuchar la frase</button><div class="it-next">⏱️ Siguiente pregunta en 4 segundos…</div>`;document.getElementById('exListen').addEventListener('click',()=>speakItalian(ex));speakItalian(ex);save();timer=setTimeout(()=>{timer=null;i++;i<q.length?render():completeLevel(ln,correct,q.length)},4000)}render()}
function completeLevel(n,correct,total){if(!state.completed.includes(n))state.completed.push(n);if(n<19)state.level=Math.max(state.level,n+1);state.xp+=50;save();document.getElementById('app').innerHTML=`<div class="it-card center"><div class="it-big">🎉</div><h2>¡Nivel completado!</h2><p>Has acertado ${correct} de ${total}.</p><p>⭐ +50 XP</p>${state.completed.length>=20?'<div class="it-unlock"><h3>🏆 ¡Has terminado Italiano A1!</h3><p>El contenido A2 se añadirá próximamente.</p></div>':''}<button class="it-main" id="cont">Continuar</button></div>`;document.getElementById('cont').addEventListener('click',showMap)}
showMap();
