/* Lingua Fun · Italiano A2 · Actualización 35 */
(function(){
const KEY='englishFunItalianState';
const levels=[
['Routine e frequenza',[['Di solito mi alzo alle sette.','Normalmente me levanto a las siete.'],['Vado in palestra tre volte alla settimana.','Voy al gimnasio tres veces por semana.'],['Quasi sempre ceno a casa.','Casi siempre ceno en casa.'],['Ogni tanto lavoro da casa.','De vez en cuando trabajo desde casa.']]],
['Città e servizi',[['Devo andare in farmacia.','Tengo que ir a la farmacia.'],['La banca è vicino alla stazione.','El banco está cerca de la estación.'],["Cerco l'ufficio postale.",'Busco la oficina de correos.'],["Sai dov'è il municipio?",'¿Sabes dónde está el ayuntamiento?']]],
['Fare acquisti e vestiti',[['Quanto costa questa giacca?','¿Cuánto cuesta esta chaqueta?'],['Posso provare questa camicia?','¿Puedo probarme esta camisa?'],['Avete una taglia più grande?','¿Tenéis una talla más grande?'],['Preferisco il modello blu.','Prefiero el modelo azul.']]],
['Al ristorante',[['Vorrei prenotare un tavolo per due.','Quisiera reservar una mesa para dos.'],['Posso avere il menù, per favore?','¿Puedo tener el menú, por favor?'],['Per me una pasta al pomodoro.','Para mí una pasta al tomate.'],['Il conto, per favore.','La cuenta, por favor.']]],
['Passato prossimo',[['Ieri ho visto un film interessante.','Ayer vi una película interesante.'],['Siamo arrivati tardi.','Llegamos tarde.'],['Hai già mangiato?','¿Ya has comido?'],['Ho dimenticato le chiavi.','He olvidado las llaves.']]],
['Viaggi e alloggio',[['Abbiamo prenotato una camera.','Hemos reservado una habitación.'],['A che ora parte il treno?','¿A qué hora sale el tren?'],['La camera non è ancora pronta.','La habitación todavía no está lista.'],['Vorrei fare il check-in.','Quisiera hacer el check-in.']]],
['Piani e futuro',[['Domani andrò a Roma.','Mañana iré a Roma.'],['Stasera incontrerò gli amici.','Esta noche quedaré con los amigos.'],['Che cosa farai nel fine settimana?','¿Qué harás el fin de semana?'],['Partiremo lunedì mattina.','Saldremos el lunes por la mañana.']]],
['Confronti',[['Questo hotel è più economico.','Este hotel es más barato.'],['Mio fratello è più alto di me.','Mi hermano es más alto que yo.'],['Questa è la soluzione migliore.','Esta es la mejor solución.'],["Il treno è meno caro dell'aereo.",'El tren es menos caro que el avión.']]],
['Salute e benessere',[['Mi fa male la testa.','Me duele la cabeza.'],['Dovresti riposarti.','Deberías descansar.'],['Ho la febbre da ieri.','Tengo fiebre desde ayer.'],['Devo prendere questo medicinale.','Tengo que tomar este medicamento.']]],
['Lavoro e studi',[['Lavoro in un’azienda internazionale.','Trabajo en una empresa internacional.'],['Devo finire questo progetto.','Tengo que terminar este proyecto.'],['Studio italiano da due anni.','Estudio italiano desde hace dos años.'],['Ho una riunione alle dieci.','Tengo una reunión a las diez.']]],
['Tecnologia e comunicazione',[['Ti mando un messaggio più tardi.','Te mando un mensaje más tarde.'],['Il mio telefono non funziona.','Mi teléfono no funciona.'],['Puoi mandarmi il file?','¿Puedes enviarme el archivo?'],['Ho dimenticato la password.','He olvidado la contraseña.']]],
['Tempo e meteo',[['Fa freddo oggi.','Hace frío hoy.'],['Domani farà bel tempo.','Mañana hará buen tiempo.'],['Quanto tempo ci vuole?','¿Cuánto tiempo se tarda?'],['Sono arrivato in anticipo.','He llegado con antelación.']]],
['Casa e problemi',[['La lavatrice non funziona.','La lavadora no funciona.'],["C'è un problema con la doccia.",'Hay un problema con la ducha.'],['Devo chiamare un tecnico.','Tengo que llamar a un técnico.'],['La porta non si chiude.','La puerta no se cierra.']]],
['Persone e relazioni',[['È una persona molto paziente.','Es una persona muy paciente.'],["Andiamo molto d'accordo.",'Nos llevamos muy bien.'],['Ci vediamo spesso.','Nos vemos a menudo.'],['Ha un carattere tranquillo.','Tiene un carácter tranquilo.']]],
['Tempo libero e cultura',[['Nel tempo libero leggo molto.','En mi tiempo libre leo mucho.'],['Mi piace andare al cinema.','Me gusta ir al cine.'],['Sabato siamo andati a un concerto.','El sábado fuimos a un concierto.'],['Quale musica preferisci?','¿Qué música prefieres?']]],
['Opinioni e connettori',[['Secondo me è una buona idea.','En mi opinión es una buena idea.'],['Penso che sia interessante.','Pienso que es interesante.'],["Sono d'accordo, però è difficile.",'Estoy de acuerdo, pero es difícil.'],['Prima di tutto dobbiamo parlare.','Primero de todo tenemos que hablar.']]],
['Imperfetto di base',[['Da bambino giocavo spesso fuori.','De niño jugaba a menudo fuera.'],['Quando ero piccolo vivevo in campagna.','Cuando era pequeño vivía en el campo.'],['Faceva molto caldo.','Hacía mucho calor.'],['Ogni estate andavamo al mare.','Cada verano íbamos al mar.']]],
['Obblighi e consigli',[['Devi studiare di più.','Tienes que estudiar más.'],['Non dovresti preoccuparti.','No deberías preocuparte.'],['Bisogna arrivare in orario.','Hay que llegar a tiempo.'],['È meglio prenotare prima.','Es mejor reservar antes.']]],
['Situazioni pratiche',[['Mi può aiutare, per favore?','¿Me puede ayudar, por favor?'],["Ho bisogno di un'informazione.",'Necesito una información.'],['Potrebbe ripetere più lentamente?','¿Podría repetir más despacio?'],['Non ho capito bene.','No he entendido bien.']]],
['Missione finale A2',[['Se domani ho tempo, andrò in centro.','Si mañana tengo tiempo, iré al centro.'],['Ieri abbiamo cenato fuori perché era il compleanno di Marco.','Ayer cenamos fuera porque era el cumpleaños de Marco.'],['Vorrei prenotare una camera per tre notti.','Quisiera reservar una habitación para tres noches.'],['Penso che questa soluzione sia migliore.','Pienso que esta solución es mejor.']]]
];
const test=[['Ieri ___ un film.','ho visto','vedevo','vedrò','vedere'],['Domani ___ a Milano.','andrò','andavo','sono andato','vado ieri'],['Dovresti ___.','riposarti','riposato','riposi','riposando'],['Quanto ___ questa giacca?','costa','costano','costare','costava ieri'],['Siamo ___ tardi.','arrivati','arrivare','arriviamo','arrivando'],['Mi ___ la testa.','fa male','fanno male','fare male','ha male'],['Secondo me ___ una buona idea.','è','sono','essere','era ieri'],['Da bambino ___ spesso fuori.','giocavo','giocherò','ho giocato ieri','giocare'],['Vorrei ___ un tavolo.','prenotare','prenotato','prenoto ieri','prenotando'],["Il treno è ___ dell'aereo.",'meno caro','meno cara','meno cari','meno care'],["Ho bisogno ___ un'informazione.",'di','a','con','perché'],['Non ho ___ bene.','capito','capire','capisco ieri','capendo'],['Ogni tanto ___ da casa.','lavoro','lavorando','lavorato','lavorerò ieri'],['Potrebbe ___ più lentamente?','ripetere','ripetuto','ripete','ripetendo'],['È meglio ___ prima.','prenotare','prenotato','prenota','prenotando']];
function st(){let s=JSON.parse(localStorage.getItem(KEY)||'{}');s.a2Unlocked=!!s.a2Unlocked;s.a2Completed=Array.isArray(s.a2Completed)?s.a2Completed:[];s.a2Level=Number.isInteger(s.a2Level)?s.a2Level:0;s.a2TestPassed=!!s.a2TestPassed;return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function sp(t){if(window.speakItalian)window.speakItalian(t)}
function es(t){if(window.speakSpanish)window.speakSpanish(t)}
function a1Done(){let s=st();let a=JSON.parse(localStorage.getItem(KEY)||'{}');return Array.isArray(a.completed)&&a.completed.length>=20}
function home(){let s=st(),app=document.getElementById('app');let locked=!s.a2Unlocked;app.innerHTML=`<div class="it-card"><div class="it-top"><button class="it-back" id="a2back">← A1</button><span>🇮🇹 Italiano A2</span></div><h1>🇮🇹 Italiano A2</h1><p>20 niveles de nivel A2, con situaciones reales, pasado, futuro, opiniones y conversación práctica.</p>${locked?`<div class="it-unlock"><h3>🔒 A2 bloqueado</h3><p>Completa Italiano A1 para desbloquearlo, o demuestra tu nivel con la prueba de acceso.</p><button class="it-main" id="access">📝 Prueba de acceso</button><button class="it-main" id="code">🔑 Código 1111</button></div>`:`<div class="it-progress"><div style="width:${s.a2Completed.length/20*100}%"></div></div><p><b>${s.a2Completed.length}/20</b> niveles completados</p><div class="it-levels">${levels.map((x,i)=>`<button class="it-level ${s.a2Completed.includes(i)?'done':''} ${i<=s.a2Level?'open':'locked'}" ${i<=s.a2Level?'':'disabled'} data-n="${i}"><b>${i+1}</b><span>${x[0]}</span><small>${s.a2Completed.includes(i)?'✓ Completado':i===s.a2Level?'▶ Empezar':'🔒 Bloqueado'}</small></button>`).join('')}</div><div class="it-unlock"><button class="it-main" id="final">📝 Prueba final A2</button></div>`}<p class="a2-note">🔜 B1 de italiano · Próximamente</p></div>`;document.getElementById('a2back').onclick=()=>location.reload();if(locked){document.getElementById('access').onclick=()=>a2Test(true);document.getElementById('code').onclick=()=>{let c=prompt('Introduce el código:');if(c==='1111'){s.a2Unlocked=true;save(s);home()}else if(c!==null)alert('Código incorrecto.')}}else{document.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>level(+b.dataset.n));document.getElementById('final').onclick=()=>a2Test(false)}}
function level(n){let s=st(),q=shuffle(levels[n][1]),i=0,score=0,timer;function render(){let [it,spn]=q[i],opts=shuffle([spn,...shuffle(q.filter((_,j)=>j!==i).map(x=>x[1])).slice(0,3)]);document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-top"><button class="it-back" id="b">← A2</button><span>🇮🇹 Nivel ${n+1}</span></div><div class="it-question-tag">A2 · ${levels[n][0]}</div><h2>${it}</h2><button class="it-listen" id="li">🔊 Escuchar en italiano</button><p>¿Qué significa?</p><div class="it-answers">${opts.map(o=>`<button>${o}</button>`).join('')}</div><div id="feedback"></div><small>Pregunta ${i+1} de 4</small></div>`;document.getElementById('b').onclick=()=>{clearTimeout(timer);home()};document.getElementById('li').onclick=()=>sp(it);setTimeout(()=>sp(it),150);document.querySelectorAll('.it-answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.it-answers button').forEach(x=>x.disabled=true);let ok=b.textContent===spn;if(ok)score++;document.getElementById('feedback').innerHTML=`<div class="it-example">${ok?'✅ <b>¡Muy bien!</b>':'❌ <b>Respuesta correcta: '+spn+'</b>'}<br>🇮🇹 ${it}<br>🇪🇸 ${spn}</div><button class="it-listen" id="esb">🇪🇸 Escuchar en español</button><div class="it-next">⏱️ Siguiente en 4 segundos…</div>`;document.getElementById('esb').onclick=()=>es(spn);sp(it);timer=setTimeout(()=>{i++;i<4?render():finish()},4000)})}function finish(){if(!s.a2Completed.includes(n))s.a2Completed.push(n);s.a2Level=Math.min(19,Math.max(s.a2Level,n+1));let base=JSON.parse(localStorage.getItem(KEY)||'{}');base.a2Unlocked=s.a2Unlocked;base.a2Completed=s.a2Completed;base.a2Level=s.a2Level;base.a2TestPassed=s.a2TestPassed;base.xp=(Number(base.xp)||0)+50;save(base);document.getElementById('app').innerHTML=`<div class="it-card center"><div class="it-big">🎉</div><h2>¡Nivel A2 completado!</h2><p>Has acertado ${score} de 4.</p><p>⭐ +50 XP</p><button class="it-main" id="c">Continuar</button></div>`;document.getElementById('c').onclick=home}render()}
function a2Test(access){let i=0,score=0;function render(){if(i>=15){let s=st(),ok=score>=14;if(ok){s.a2Unlocked=true;s.a2TestPassed=true;s.a2Level=Math.max(s.a2Level,0);save(s)}document.getElementById('app').innerHTML=`<div class="it-card center"><div class="it-big">${ok?'🎉':'📚'}</div><h2>${ok?'¡Prueba superada!':'Todavía no'}</h2><p>${score}/15 correctas.</p><p>${ok?'Italiano A2 está desbloqueado.':'Necesitas al menos 14/15 (90%). Puedes repetirla.'}</p><button class="it-main" id="r">${ok?'Entrar en A2':'Repetir prueba'}</button></div>`;document.getElementById('r').onclick=ok?home:()=>a2Test(access);return}let q=test[i],opts=shuffle(q.slice(1));document.getElementById('app').innerHTML=`<div class="it-card"><div class="it-top"><span>📝 ${access?'Prueba de acceso':'Prueba final'} A2</span></div><h2>Pregunta ${i+1}/15</h2><div class="it-question-tag">${q[0]}</div><div class="it-answers">${opts.map(o=>`<button>${o}</button>`).join('')}</div><div id="feedback"></div></div>`;document.querySelectorAll('.it-answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.it-answers button').forEach(x=>x.disabled=true);let good=b.textContent===q[1];if(good)score++;document.getElementById('feedback').innerHTML=good?'<div class="it-example">✅ Correcto</div>':'<div class="it-example">❌ Correcta: <b>'+q[1]+'</b></div>';setTimeout(()=>{i++;render()},1800)})}render()}
function addButton(){if(document.getElementById('itA2Button'))return;let card=document.querySelector('.it-card');if(!card)return;let b=document.createElement('button');b.id='itA2Button';b.className='it-main';b.textContent='🇮🇹 Entrar en Italiano A2';b.onclick=home;let unlock=card.querySelector('.it-unlock');if(unlock)unlock.parentNode.insertBefore(b,unlock);else card.appendChild(b);}
window.addEventListener('load',()=>setTimeout(addButton,250));
})();
